name = "PowerPlotsMakie"
uuid = "49f9eb5c-8e5a-55cd-abba-b3fc827ff2f8"
version = "0.1.0"
authors = ["Stefan de Lange <langestefan@msn.com>"]

[workspace]
projects = ["test", "docs", "examples"]

[deps]
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"

[compat]
GraphMakie = "0.6.6"
julia = "1.10"
